version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql-inv
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  inventory:
    build: .
    container_name: inventory
    ports:
      - "8082:8082"
    depends_on:
      - mysql
