services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: orderdb
    ports:
      - "3306:3306"
    volumes:
      - ./odb:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

#  om-order:
 #   build: .
  #  container_name: om-order
   # ports:
    #  - "8081:8081"
    #depends_on:
     # - orderdb