apiVersion: v1
kind: Service
metadata:
  name: om-order-svc #hostname for API, with 'port'
spec:
  type: NodePort # for internal-only service, use ClusterIP
  ports:
  - targetPort: 8081
    port: 8081 #port for API, with 'name' of service
    nodePort: 32081 #only for NodePort service type
  selector: #pod definition
    app: om-order
    subnet: backend

#kubectl create -f order-service.yml
#kubectl get services
##kubenetes
##om-order

# NodePort is the externally accessible port to access API etc., in the range of 30000 to 32767
