apiVersion: v1
kind: Service
metadata:
  name: om-product-svc #hostname for API, with 'port'
spec:
  type: NodePort # for internal-only service, use ClusterIP
  ports:
  - targetPort: 8080
    port: 8080 #port for API, with 'name' of service
    nodePort: 32080 #only for NodePort service type
  selector: #pod definition
    app: om-product
    subnet: backend

#kubectl create -f product-service.yml
#kubectl get services
##kubenetes
##om-product

# NodePort is the externally accessible port to access API etc., in the range of 30000 to 32767
