apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: om-product-rs
  labels:
    app: om-product
    subnet: backend
spec:
  template:
    metadata:
      name: product
      labels:
        app: product
        subnet: backend
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0.5
      - name: product
        image: i50729/om-product
  replicas: 1
  selector:
    matchLabels:
          subnet: backend
#kubectl create -f product-replicaset.yml
#kubectl get replicasets