version: '4'
services:
  auth-keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    container_name: auth-keycloak
    command: [ "start-dev","--import-realm" ]
    environment:
      DB_VENDOR: mysql
      DB_ADDR: mysql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    volumes:
      - ./docker/keycloak/realms/:/opt/keycloak/data/import/
    depends_on:
      - auth-keycloak-mysql
  auth-keycloak-mysql:
    image: mysql:8.3.0
    container_name: auth-keycloak-mysql
    environment:
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/auth_keycloak_mysql_data:/var/lib/mysql
