apiVersion: v1
kind: Service
metadata:
  name: om-order-svc #hostname for API, with 'port'
  labels:
    app: om-order
    side: backend

spec:
  type: NodePort # elsewise for internal-only service, must use ClusterIP
  ports:
  - targetPort: 8080 #internal app port
    port: 8080 #port for API, with 'name' of service, similar to mysql:3306 socket; it is mandatory
    nodePort: 32080 #only for NodePort service type, accessible to external users, curl and web browsers;range is 30000 to 32767
  selector: #from pod definition
    app: om-order
    side: backend

## to create a service
#kubectl create -f order-service.yml

## to check the service status
#kubectl get services
###NAME     TYPE    CLUSTER-IP  EXTERNAL-IP PORT(S) AGE headers are listed

#4
#2