services:
  productdb:
    image: mongo:7.0.5
    container_name: productdb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - ./productdb:/data/db

  om-product:
    build: .
    container_name: om-product
    ports:
      - "8080:8080"
    depends_on:
      - productdb

  mongo-express:
    image: mongo-express
    ports:
      - "8090:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_ROOT_USER}:${DB_ROOT_PASSWORD}@localhost:27017/
      ME_CONFIG_BASICAUTH: true
    depends_on:
      - productdb