services:
  orderdb:
    image: mysql:8.3.0
    container_name: orderdb
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: orderdb
    ports:
      - "3306:3306"
    volumes:
      - ./orderdb:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      #pw hint

#  om-order:
 #   build: .
  #  container_name: om-order
   # ports:
    #  - "8081:8081"
    #depends_on:
     # - orderdb