services:
  invmysql:
    image: mysql:8.3.0
    container_name: invmysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DBNAME}
    ports:
      - "3307:3306"
    volumes:
      - ./invdb:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
