version: '4'
services:
  #TODO to declare Kafka consumer
  #kafka-consumer:

  notification:
    build: ./notification
    container_name: notification
    ports:
      - "9092:9092"
    #depends_on:
     # - kafka-consumer
