apiVersion: apps/v1
kind: Deployment
metadata:
  name: om-product-kt-depl #shown in listing, also specified in scale command
  labels:
    app: om-product-kt
    side: backend
spec:
  template:
    metadata:
      name: om-product-kt-pod
      labels:
        app: om-product-kt
        side: backend
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0.5
        volumeMounts:
          - name: productdb
            mountPath: /data/productdb
      - name: om-product-kt
        image: localhost:5000/om-product-kt
  replicas: 1
  selector:
    matchLabels:
      app: om-product-kt
      side: backend
#kubectl create -f product-kt-deployment.yml
#kubectl get deployments
#kubectl get replicasets
#kubectl get pods

# to update container sepcs
##kubectl apply -f depl-desc.yml -- after changing container name or image tag
##kubectl set image deployment/prod-depl-name mongodb=mongo:8.0.1

#kubectl delete deployment depl-name