apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: om-product-rs #shown in listing, also specified in scale command
  labels:
    app: om
    name: om-product-rs
    side: backend
spec:
  template:
    metadata:
      name: om-product-pod
      labels:
        app: om
        side: backend
    spec:
      containers:
      - name: productdb
        image: mongo:7.0.5
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: cm9vdAo=
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: cGFzc3dvcmQK
          - name: MONGO_INITDB_DATABASE
            value: cHJvZHVjdGRiCg==
        ports:
          - containerPort: 27017
        command: ['sh', '-c', 'echo "The Product app is running!"]
        volumeMounts:
          - name: productdb
            mountPath: /data/productdb
      - name: om-product
        image: localhost:5000/om-product
        imagePullPolicy: Never
        ports:
          - containerPort: 8080

  replicas: 1
  selector:
    matchLabels:
      app: om
      name: om-product-rs
      side: backend
#kubectl create -f product-replicaset.yml
#kubectl get replicasets

# to update replica count
##kubectl replace -f product-replicaset.yml -- after changing replicas value in file
##kubectl scale --replicas=2 -f product-replicaset.yml
##kubectl scale --replicas=3 replicaset om-product-rs

#kubectl delete replicaset om-product-rs