apiVersion: apps/v1
kind: Deployment
metadata:
  name: om-product-depl #shown in listing, also specified in scale command
  labels:
    app: om
    name: om-product-depl
    side: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: om
      name: om-product-pod
      side: backend
  template:
    metadata:
      name: om-product-pod
      labels:
        app: om
        name: om-product-pod
        side: backend
    spec:
      containers:
        - name: om-product
          image: localhost:5000/om-product
          ports:
            - containerPort: 8080
#kubectl create -f product-deployment.yml
#kubectl get deployments
#kubectl get replicasets
#kubectl get pods

# to update container sepcs
##kubectl apply -f product-deployment.yml -- after changing container name or image tag
##kubectl set image deployment/om-product-depl mongodb=mongo:8.0.1

#kubectl delete deployment om-product-depl