apiVersion: v1
kind: Pod
metadata:
  name: om-product-pod
  labels:
    app: om
    name: om-product-pod
    side: backend

spec:
  containers:
  - name: om-product
    image: localhost:5000/om-product
    imagePullPolicy: Never
    ports:
      - containerPort: 8080


## create pod
#kubectl apply -f product-pod.yml

## view pods
#kubectl get pods

## view pod details
#kubectl describe pod om-product-pod

#1
#1

#20250518