apiVersion: v1
kind: Pod
metadata:
  name: om-product-kt-pod
  labels:
    app: om-product-kt
    side: backend

spec:
  containers:
  - name: mongodb
    image: mongo:7.0.5
    env:
      - name: MONGO_INITDB_ROOT_USERNAME
        value: cm9vdAo=
      - name: MONGO_INITDB_ROOT_PASSWORD
        value: cGFzc3dvcmQK
      - name: MONGO_INITDB_DATABASE
        value: cHJvZHVjdGRiCg==
    ports:
      - containerPort: 27017
    command: ['sh', '-c', 'echo "The Product app is running!"]
    volumeMounts:
      - name: productdb
        mountPath: /data/productdb
  - name: om-product-kt
    image: localhost:5000/om-product-kt
    imagePullPolicy: Never
    ports:
      - containerPort: 8081


## create pod
#kubectl apply -f product-kt-pod.yml

## view pods
#kubectl get pods

## view pod details
#kubectl describe pod om-product-kt-pod

#1
#1