apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: om-product-rs #shown in listing, also specified in scale command
  labels:
    app: om-product
    subnet: backend
spec:
  template:
    metadata:
      name: om-product
      labels:
        app: om-product
        subnet: backend
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0.5
      - name: om-product
        image: i50729/om-product
  replicas: 1
  selector:
    matchLabels:
      subnet: backend
#kubectl create -f product-replicaset.yml
#kubectl get replicasets

# to update replica count
##kubectl replace -f rs-desc.yml -- after changing replicas value in file
##kubectl scale --replicas=2 -f rs-desc.yml
##kubectl scale --replicas=3 replicaset om-product-rs

#kubectl delete replicaset rs-name