apiVersion: v1
kind: Pod
metadata:
  name: om-product-pod
  labels:
    app: om-product
    subnet: backend
spec:
  containers:
  - name: mongodb
    image: mongo:7.0.5
  - name: om-product
    image: i50729/om-product

#kubectl apply -f product-pod.yml
#kubectl get pods