apiVersion: apps/v1
kind: Deployment
metadata:
  name: om-product-rs #shown in listing, also specified in scale command
  labels:
    app: om-product
    subnet: backend
spec:
  template:
    metadata:
      name: om-product
      labels:
        app: om-product
        subnet: backend
    spec:
      containers:
      - name: mongodb
        image: mongo:7.0.5        
      - name: om-product
        image: i50729/om-product
  replicas: 1
  selector:
    matchLabels:
      subnet: backend
#kubectl create -f product-deployment.yml
#kubectl get deployments
#kubectl get replicasets
#kubectl get pods

# to update container sepcs
##kubectl apply -f depl-desc.yml -- after changing container name or image tag
##kubectl set image deployment/prod-depl-name mongodb=mongo:8.0.1

#kubectl delete deployment depl-name